version: '3.8'

services:

  database:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    hostname: oaken-postgres
    container_name: oaken-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - oaken-postgres:/var/lib/postgresql/data
      - ./app/mysql-startup/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oaken

  invoice-processor:
    image: oaken-invoice
    env_file:
      - .env
    restart: unless-stopped
    hostname: invoice-processor
    container_name: invoice-processor
    volumes: 
      - invoice-processor:/app
    networks:
      - oaken
    depends_on:
      - database

  shipping-processor:
    image: oaken-shipping
    env_file:
      - .env
    restart: unless-stopped
    hostname: shipping-processor
    container_name: shipping-processor
    volumes: 
      - oaken-shipping:/app
    networks:
      - oaken
    depends_on:
      - database

  accounting-processor:
    image: oaken-accounting
    env_file:
      - .env
    restart: unless-stopped
    hostname: accounting-processor
    container_name: accounting-processor
    volumes: 
      - oaken-accounting:/app
    networks:
      - oaken
    depends_on:
      - database

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: oaken-dbeaver
    hostname: oaken-dbeaver
    restart: unless-stopped
    ports:
      - 8978:8978
    volumes: 
      - oaken-cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - oaken
    depends_on:
      - database

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - oaken

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    restart: unless-stopped
    ports:
      - "19092:19092"
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://kafka1:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - oaken

  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka2
    container_name: kafka2
    restart: unless-stopped
    ports:
      - "19093:19093"
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL://kafka2:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL://localhost:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - oaken

  kafka3:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka3
    container_name: kafka3
    restart: unless-stopped
    ports:
      - "19094:19094"
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka3:9094,EXTERNAL://kafka3:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9094,EXTERNAL://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - oaken

  setup-topics:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zoo1
      - kafka1
      - kafka2
      - kafka3
    command: /bin/bash -c "/scripts/create-topics.sh"
    volumes:
      - ./create-topics.sh:/scripts/create-topics.sh:ro
    networks:
      - oaken


networks:
  oaken:

volumes:
  oaken-postgres:
    name: oaken-postgres
  invoice-processor:
    name: invoice-processor
  oaken-shipping:
    name: oaken-shipping
  oaken-accounting:
    name: oaken-accounting
  oaken-cloudbeaver:
    name: oaken-cloudbeaver