FROM python:3.11

RUN apt-get update && \
    apt-get install -y pkg-config && \
    pip install kafka-python psycopg2 && \
    mkdir -p /app && \
    apt-get clean

COPY /app/mysql-api/invoice-api-docker.py /app

WORKDIR /app

CMD ["python", "invoice-api-docker.py"]
