FROM python:3.11

RUN apt-get update && \
    apt-get install -y pkg-config && \
    pip install kafka-python mysql-connector-python && \
    mkdir -p /app && \
    apt-get clean

COPY app/accounting/accounting.py /app

WORKDIR /app

CMD ["python", "accounting.py"]