version: '3.8'

services:
  database-mysql:
    image: mysql:latest
    env_file:
      - .env
    restart: always
    hostname: oaken-mysql
    container_name: oaken-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes: 
      - oaken-mysql:/var/lib/mysql
      - ./app/mysql/init.sql:/data/application/init.sql
    networks:
      - OakenSpirits

  mysql-kafka-processor:
    image: oaken-mysql-kafka
    env_file:
      - .env
    restart: always
    hostname: mysql-kafka-processor
    container_name: mysql-kafka-processor
    volumes: 
      - oaken-api:/app
    networks:
      - OakenSpirits

  shipping-processor:
    image: oaken-shipping
    env_file:
      - .env
    restart: always
    hostname: shipping-processor
    container_name: shipping-processor
    volumes: 
      - oaken-shipping:/app
    networks:
      - OakenSpirits

  accounting-processor:
    image: oaken-accounting
    env_file:
      - .env
    restart: always
    hostname: accounting-processor
    container_name: accounting-processor
    volumes: 
      - oaken-accounting:/app
    networks:
      - OakenSpirits

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: oaken-dbeaver
    hostname: oaken-dbeaver
    restart: on-failure:5
    ports:
      - 8978:8978
    volumes: 
      - oaken-cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - OakenSpirits

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: oaken-zookeeper
    container_name: oaken-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - OakenSpirits

  kafka1:
    image: confluentinc/cp-kafka:7.1.0
    hostname: oaken-kafka1
    container_name: oaken-kafka1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - oaken-kafka:/create-topics.sh
    command: ["/bin/bash", "-c", "/create-topics.sh"]
    networks:
      - OakenSpirits

  kafka2:
    image: confluentinc/cp-kafka:7.1.0
    hostname: oaken-kafka2
    container_name: oaken-kafka2
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - OakenSpirits

  create-topics:
    image: confluentinc/cp-kafka:7.1.0
    depends_on:
      - kafka1
    command: ["kafka-topics", "--create", "--zookeeper", "zookeeper:2181", "--replication-factor", "1", "--partitions", "1", "--topic", "mysql"]

  invoice-topic:
    image: confluentinc/cp-kafka:7.1.0
    depends_on:
      - kafka1
    command: ["kafka-topics", "--create", "--zookeeper", "zookeeper:2181", "--replication-factor", "1", "--partitions", "1", "--topic", "invoices"]

  shipping-topic:
    image: confluentinc/cp-kafka:7.1.0
    depends_on:
      - kafka1
    command: ["kafka-topics", "--create", "--zookeeper", "zookeeper:2181", "--replication-factor", "1", "--partitions", "1", "--topic", "shipping"]

networks:
  OakenSpirits:

volumes:
  oaken-mysql:
    name: oaken-mysql
  oaken-api:
    name: oaken-api
  oaken-shipping:
    name: oaken-shipping
  oaken-accounting:
    name: oaken-accounting
  oaken-cloudbeaver:
    name: oaken-cloudbeave
  oaken-kafka:
    name: oaken-kafka
