dbt_project:
  outputs:
    dev:
      dataset: oaken_transformed
      job_execution_timeout_seconds: 300
      job_retries: 1
      # Use an env variable to indicate your JSON key file path
      # keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE_PATH', '') }}"
      keyfile: "/home/blackitalian/.ssh/airbyte-bigquery.json"
      location: US
      method: service-account
      priority: interactive
      # Indicate your BigQuery project ID
      project: elaborate-art-318223
      threads: 1
      type: bigquery
  target: dev